### ISSUE TITLE
Add Contract deployment support

### ISSUE THREAD

**Issue by kautukkundan** [jzaki/bls-wallet#182]
Aggregator throws error when trying to submit a contract deployment transaction

![Screenshot 2022-04-04 at 4 39 57 PM](https://user-images.githubusercontent.com/23727056/161536136-22cfdd19-19a6-4e97-8348-1be4f56d3d1b.png)

**Comment by jacque006** [comment]
What was the contract deployment needed for in this case?

**Comment by kautukkundan** [comment]
for the BLS account to be able to deploy any new contract. 

In case of contract deployment the tx body looks like 
```ts
{
  from: "<SENDER_ADDR>",
  to: "0x",
  value: "<ETH_VALUE>",
  data: "<DEPLOYMENT_DATA>"
}
```
So the aggregator crashes when the "to" field contains a zero/null value

**Comment by voltrevo** [comment]
Contract changes needed for this because `_performOperation` only implements paid/non-paid actions (to existing addresses):

```solidity
a = op.actions[i];
if (a.ethValue > 0) {
    (success, result) = payable(a.contractAddress).call{value: a.ethValue}(a.encodedFunction);
}
else {
    (success, result) = address(a.contractAddress).call(a.encodedFunction);
}
require(success);
results[i] = result;
```
https://github.com/web3well/bls-wallet/blob/4dae24f/contracts/contracts/BLSWallet.sol#L179-L187

We need a new branch for contract creation, possibly using something like this:
```solidity
assembly {
    addr := create(0,add(code,0x20), mload(code))
    jumpi(invalidJumpLabel,iszero(extcodesize(addr)))
}
```
https://ethereum.stackexchange.com/a/11129

Parking this for now since we've decided not to implement it in V1:
https://discord.com/channels/943612659163602974/963404009266376774/1008748869514969200

**Comment by jzaki** [comment]
Will need an extra flag in `ActionData` to be signed with txs (a `bool` in a struct is stored as a one byte).
