### ISSUE TITLE
Add ability for bls-wallet-clients to generate a determinisitc hash of a bundle

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#192]
A la ETH transaction hashes (https://stackoverflow.com/a/57638023), we should add a bundle hashing function to `bls-wallet-clients` so that the hash for a bundle can be determined at will.
- Add bundle hashing function to `bls-wallet-clients`. There may be a general ETH/MetaTransaction spec for this that we should adhere to.
- Replace existing `makeHash` function in aggregator with this.

**Comment by voltrevo** [comment]
I feel this is tricky because bundles are expected to be combined into larger bundles before submitting on chain, so there isn't going to be an on-chain representation of what we're hashing.

In the meantime, the lack of meaning in the random 'hash' actually has the advantage of not breaking anyone's expectations if we find a suitable meaning for these hashes to use in the future, like the possibility of a "general ETH/MetaTransaction" spec you refer to.

I'm inclined to leave this as random for now. @jacque006 @jzaki wdyt?

**Comment by jzaki** [comment]
What about using the aggregated signature, or part there of? It's deterministic and unique to bundles (aggregate of UserOp sigs).

**Comment by jacque006** [comment]
I think it is useful to have deterministic hashes for our bundles/ops, so that end users/applications can generate the same hash an agg would without needing to connect/submit to one, and it provides a quick and easy way to compare two bundles to see if they are equal. We should try to match the existing behavior of transactions when possible, except when deviation is necessary.

The complexity comes in mapping a sub bundle/ops to the larger bundle that was submitted, and knowing that the sub bundle is part of the submitted bundle. We could more reliably do this if we hashed a UserOp without the signature, then a bundle becomes a list of hashes and it becomes easy to do a reverse lookup. Would be interesting to see how EIP-4337 is handling that as well.
