### ISSUE TITLE
Add recovery to extension

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#281]
Using this mechanism:
https://github.com/web3well/bls-wallet/blob/main/contracts/contracts/VerificationGateway.sol#L196

Let users know that multisig may be a good combo when doing this.

Probably some overlap with:
https://github.com/web3well/bls-wallet/issues/220

**Comment by kautukkundan** [comment]
related #220

**Comment by blakecduncan** [comment]
I caught up with James on this ticket and will explain the expected UX below

In the Instant wallet
- The users sets the recovery hash using an address in the Quill extension (ex: wallet 0) and arbitrary salt
- After the hash is set the user can click to copy the salt and the Instant wallet smart contract address. These can then be used in the quill extension to recover the wallet

In the quill extension
- The user must input the salt and the smart contract address from above
- We will use the smart contract address to look up the bls key hash (this is the hash of the instant wallet) and the quill extension will generate a new bls key.  With the hash, salt, new bls key and signature from the existing wallet (ex: wallet 0) in the quill extension we can call the `recoverWallet` function

@jzaki just want to confirm this is correct?
Also, FYI @kautukkundan

**Comment by jzaki** [comment]
To nest it a little more:

1. User installs quill extension (eg first-time web3 users upgrading their instant wallet to a more secure one)
  - first bls wallet address in quill to be used as recovery address
  - this must be funded with some eth to recover the instant wallet

2. In the Instant wallet
  - The user sets the recovery hash using an address in the Quill extension (ex: wallet 0) and arbitrary salt
  - After the hash is set (regular transaction toast) the user can click a button in the recovery menu to copy the salt and the Instant wallet smart contract address (convenience for recovery params)
  - These can then be used in the quill extension to recover the wallet

3. In the quill extension
  - Instead of "add" wallet, user clicks button to "recover a wallet" a bls wallet
  - The user must input (just paste?) the salt and the smart contract address copied from above
  - On user confirmation, the extension will:
    - use the smart contract address to look up the bls key hash (**_param2_**) (this is the hash of the instant wallet's bls key)
    - generate a new bls key to replace that of the instant wallet (**_param 4_**)
    - sign the instant wallet address with the new bls key (signatures is **_param 1_**)
    - With the 4 params: signature, hash, salt (**_param 3_**), and new bls key; call `recoverWallet` from wallet 0
      - (ie create the transaction, sign with wallet 0's bls key, then submit signed tx to aggregator)

**Comment by jacque006** [comment]
Resolved via https://github.com/web3well/bls-wallet/pull/342
