### ISSUE TITLE
Remove hardcoded passcode for encryption

### ISSUE THREAD

**Issue by kautukkundan** [jzaki/bls-wallet#289]
I thought for a first PR it would be good to just get the encryption working.  I figure as a separate PR I'll store the pass key in memory.

If anyone has any recommendations on how I should do that, let me know.  I know that metamask uses [obs-store](https://www.npmjs.com/package/obs-store) to keep the password in memory.

_Originally posted by @blakecduncan in https://github.com/web3well/bls-wallet/pull/286#discussion_r929759988_

**Comment by jacque006** [comment]
I think as long as you clearly label it as a password, and we have some window where it will be cleared due to inactivity or just after a certain amount of time you can use almost anything. Might make sense as a cell.

**Comment by blakecduncan** [comment]
> I think as long as you clearly label it as a password, and we have some window where it will be cleared due to inactivity or just after a certain amount of time you can use almost anything. Might make sense as a cell.

@jacque006 I've been thinking I might have to do that.  The original plan was to keep the CryptoKey in memory for encoding and decoding the data.  But I've been stuck on that because if I keep the key in memory in the background script then I don't think it's easy for the extension dapp to access the key.  And we read/write to local storage from both the dapp and the background script.

Update: I just realised we have memory cells and local cells.  It would be great if I could use a memory cell but I'm not sure how I can easily pass it back and forth between the background script and the dapp.  Which is making me think I would need a local cell.
