### ISSUE TITLE
Issue sending Eth in the Quill wallet

### ISSUE THREAD

**Issue by blakecduncan** [jzaki/bls-wallet#295]
I noticed an issue when attempting to send Eth using the Quill wallet.  The bundle is successfully submitted to the aggregator.  However, when it tries to run the aggregation strategy on the bundle it comes back failed.

Tracing the code, I first noticed the bundle is failed when we call `es.callStaticSequenceWithMeasure()` in the `#measureFees()` function of the aggregation strategy.  I think we may be swallowing an error or something because I have not be able to figure out what the issue is.

**Comment by voltrevo** [comment]
> Just wanted to give an update on this issue https://github.com/web3well/bls-wallet/issues/295.  Andrew and I paired up on it this morning and got it working.  Turns out it wasn't a bug.  It was due to different versions of the bls client module being used between the contracts and the extension.  Because of this the extension and contracts would generate different addresses which would lead to an insufficient funds error when submitting a transaction.  To fix the issue locally we had to checkout an old commit, start up the hard had node and deploy the contracts on the old commit.  This definitely seems like a developer experience issue.  Talking with Andrew it sounds like this could be something we try to make better after the audit.

https://discord.com/channels/943612659163602974/963404009266376774/1007578678135373936

To solve this I believe we should start cutting releases for contracts. Contracts development should happen on its own branch so that developers will see the version that is deployed on testnets and compatible with the extension by default. We should add a note about this in the contracts readme.

In the meantime, we can advise this workaround which isn't too difficult:
https://github.com/web3well/bls-wallet/pull/304

If the audited version of the contracts is only a week or two away then it's probably worth waiting for that version. Otherwise, I think it's reasonable to simply cut a release now to prevent further confusion. @jzaki wdyt?

**Comment by voltrevo** [comment]
Solved by #304.
