### ISSUE TITLE
Update and run gas measurement script

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#311]
Script likely needs updating, and when run against #310, should be able to do more than 29 txs.
Array [here](https://github.com/web3well/bls-wallet/blob/main/contracts/scripts/test/measure_gas.ts#L19) can be the number of UserOperations to try in a bundle, eg: `[20, 40 , 80, 120]`, it will fail once the bundle is too large for the chain's transaction.

Previuosly on Arbitrum testnet there was a limit to the number of curve operations per tx, this limit is not present in Nitro.

**Comment by voltrevo** [comment]
I think we should update this to measure L1 and L2 gas.

In my understanding (which needs to be confirmed), L1 gas is calculated using the raw transaction (including not just `data` but the ecdsa signature etc) and charging 16 gas for non-zero bytes and 3 gas for zero bytes.

Point of uncertainty: Arbitrum does compression before rolling up to L1. We might need to do some similar preprocessing on the calldata before running the above calculation.

L2 gas can be calculated using a wrapper contract which calls `gasleft()` before and after forwarding that data to the real contract (gateway/expander), and doing the subtraction. You also probably need to add the calldata gas calculated for L1 but this is relatively small.

After calculating those two things, the gas limit/usage reported by arbitrum should correspond to:

```
gas = L2gas + L1gas * L1gasPrice/L2gasPrice
```

To understand this conceptually: Arbitrum needs to report a single gas value for compatibility reasons. It does this by starting with actual L2 gas, and then adds a conversion of L1 gas into an amount of L2 gas that would cost the same amount.

This (L1gas, L2gas) pair is a much more useful measurement because otherwise 'gas' is dependent on relative L1/L2 gas prices, and therefore fluctuates all the time. This is especially a problem if 'gas' is measured using Arbitrum Goerli. 'gas' from Arbitrum Goerli has no meaning outside of Arbitrum Goerli.

More info: [Understanding Arbitrum: 2-Dimensional Fees](https://medium.com/offchainlabs/understanding-arbitrum-2-dimensional-fees-fd1d582596c9).

Also btw:

![Image](https://user-images.githubusercontent.com/9291586/214472814-97bc22f7-b4e6-4202-9650-15ab2a544639.png)

**Comment by jacque006** [comment]
@voltrevo I believe I have this covered in pending updates with [gasUsedForL1](https://github.com/web3well/bls-wallet/pull/341/files#diff-defba079f39ed2bb8e5b788a55fa4ea216963c871a1864e9cf5879b5c1684b43R9-R16), which can be subtracted from total gas to derive L2 compute/memory/etc costs.

**Comment by voltrevo** [comment]
As discussed, `gasUsedForL1` is not the L1 gas measurement that we need. It's important to instead think of `gasUsedForL1` as a fudge factor that is not meaningful outside of the current gas prices on L1 and L2.

Keen to keep working to demystify this.

**Comment by jzaki** [comment]
"fudge factor" suggests an uncertain adjustment, my understanding is that it is based on a calculation of the amount of data required on L1 (post compression), EDIT: and what that L1 cost is when paid in L2 gas prices.
Will see if someone from Arbitrum gets back to you regarding the multi-dim gas article comment, will also link to the Arbitrum dev we spoke with at DevCon.

**Comment by voltrevo** [comment]
> "fudge factor" suggests an uncertain adjustment

@jzaki Oh yeah I didn't mean it like that. What I meant to convey is that the adjustment is awkward and confusing because it uses the strategy of "I can only charge for Y, but you're buying X... I'll just charge you for more Ys to make up for it".

Like eg imagine a grocery store that sells apples and oranges, but can only charge you for oranges. You buy a basket of 10 apples and 50 oranges, and they charge you 150 oranges. They put "100 oranges charged for apples" on the bill - this is what I'm calling a fudge factor. What they really wanted to do was put apples on your bill, but they had to *fudge* it by inflating the number of oranges instead.

Note that the bill has enough information to figure out how many oranges you bought (150-100=50) but not how many apples you bought (100 oranges worth of apples... so you'd need to go and find the orange/apple price ratio to figure it out).
