### ISSUE TITLE
ABI Decode results from actions in an operation

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#364]
**As a** developer,
**I want** a client function that decodes the results of actions in an executed operation
**So that** I can extract results data in a structured, human readable way

## Considerations
 - Results should be decodable into a TS/JS struct (maybe with ts-io validation?) so they can be easily usable in client consumers.

**Comment by voltrevo** [comment]
@jacque006 Is this about decoding the return value of `verificationGateway.callStatic.processBundle(...)`?

If so, I feel like a guide might be better than supplying a new function - using that function could be more complicated than the code inside it.

The way to do this is to use `contract.interface.decodeFunctionResult` with the appropriate `contract`(s) used (which we don't have in the bundle, so they need to be passed in anyway).

Curiously, typechain doesn't provide accurate types for `decodeFunctionResult`, e.g.:

```ts
// MockERC20.d.ts
// ...
export interface Result extends ReadonlyArray<any> {
    readonly [key: string]: any;
}
// ...
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result; // <--- Not BigNumber? :(
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
```

We could help out by providing a utility that fills in that gap, similar to what we're doing internally here:

```ts
type DecodeReturnType<
  Contract extends BaseContract,
  Method extends keyof Contract["callStatic"],
> = EnforceArray<AsyncReturnType<Contract["callStatic"][Method]>>;
```

- https://github.com/web3well/bls-wallet/blob/a8534c5/aggregator/src/app/EthereumService.ts#L62-L65

Preferably, it would be nice to contribute improved type generation for [typechain](https://github.com/dethcrypto/TypeChain). (In addition to the guide/functionality for decoding `processBundle`, since it would simplify that work.)

**Comment by jacque006** [comment]
@voltrevo The idea was to do it off the event data, similarly to https://github.com/web3well/bls-wallet/pull/366/files#diff-674eb8bdeb284c750de53a656e2bf4afba3c0a81c9d9024dcab7617150c6557cR77 . That way people could get the results of the action function calls.

Now that I am thinking about it more, that is a rather uncommon situation. It would be more likely that someone would want to get the events & related data for each action, as that is how you can get the results of most other transactions. We could change/add to this just returning the subset of events that happened in an action or operation. Thoughts?

**Comment by voltrevo** [comment]
Yeah definitely keen to extract the events for each action.

To be clear though, those events will need to be in a raw form though, right? The 'decoding' is just about finding the binary sequences associated with each action?

From there, to find out what they 'really' mean, dApps/wallets need to associate those logs with the application-specific contract calls being made.

**Comment by jacque006** [comment]
Right, a dApp/wallet needs to tell us how to decode those action results, but we *might* be able to do that automatically by using the `contractAddress` and the methodID selector from the beginning of `encodedFunction` from the operation action(s) to construct a `decodeFunctionResult` for each action.

The next difficult part from there is to get the right TS type for that result. We *might* be able to do that if we have the contract ABI and can run that through typechain, but we would need to use something like etherscan, sourcify, or another contract ABI registry to get the ABI from `contractAddress`. Assuming we did all of this in `getOperationResults`, it could add a lot of RPC overhead unless they have a bulk call endpoint.

We could make a default contract ABI resolver, and allow consumers to override it with their own custom one. Consumers may only care about certain ops if the agg that submitted contains a mix of multi wallet/dApp txns.
