### ISSUE TITLE
Update contract deployment to use safe singleton factory

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#394]
Now that we have safe singleton factory (https://github.com/web3well/bls-wallet/issues/331#issuecomment-1308126246), update our contract deployment code to make use of this, allowing the contracts to be deployed to a deterministic address without relying on special keys.

**Comment by voltrevo** [comment]
This requires some care to pass constructor arguments. Just using the bytecode as I did [here](https://github.com/voltrevo/arb1-exp-nov-2022/blob/a929341/scripts/create2FreeMoney.ts#L36) is correct if you don't have any constructor arguments.

I think the solution is to use `ContractFactory.createInterface().encodeDeploy(...constructor args)`, but this isn't the full deployment code as you might expect. Instead, I think you need to append this result to the end of the bytecode.

**Comment by jzaki** [comment]
Whilst this issue is worth completing, in the future this should not be required. Systems above addresses, like ENS and relevant CAIPs, should be able to provide a good ux for users to not make mistakes between chains.
https://forum.gnosis-safe.io/t/how-can-a-safe-hold-asset-on-multiple-chains/2242/11
