### ISSUE TITLE
Aggregator hardening

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#403]
Identify & pursue issues that would be barriers to running a non-test aggregator

- [x] https://github.com/web3well/bls-wallet/issues/415
- [x] https://github.com/web3well/bls-wallet/issues/416
- [ ] https://github.com/web3well/bls-wallet/issues/389 - being dealt with separately 
- [x] #453

**Comment by jacque006** [comment]
One thing I know we will need to do is move from storing submitted bundles in memory to the db https://github.com/web3well/bls-wallet/issues/190

The other is bootstrapping/syncing chain state on first start/restarts https://github.com/web3well/bls-wallet/issues/191

**Comment by jacque006** [comment]
Also worth considering a production infra situation where more than one agg instance is running at a time. Some things should work running off the same postgres db, but I imagine some other things would break such as aggs trying to submit the same bundles/ops without being aware the other agg has already done so.

We could also move of of a postgres instance to internal storage such as SQLite or LevelDB so that agg instances can run independently and without operators needing to spin up separate db resources.

**Comment by voltrevo** [comment]
https://github.com/web3well/bls-wallet/issues/415

EDIT: Added to list in description

**Comment by voltrevo** [comment]
@jacque006 

> We could also move of of a postgres instance to internal storage such as SQLite or LevelDB so that agg instances can run independently and without operators needing to spin up separate db resources.

Yeah the storage is local to the aggregator, so I've kinda wanted to just move to SQLite since the early days. That's not a necessary improvement... but I would like to do it. Probably not right now.

I believe the idea for sharing bundles is a future unrelated enhancement to do something similar to the L1 mempool.

**Comment by voltrevo** [comment]
@jacque006

> One thing I know we will need to do is move from storing submitted bundles in memory to the db https://github.com/web3well/bls-wallet/issues/389

I think you pasted the wrong issue link there. Do you know if there's a different one for it? (Also want to talk about this issue.)

**Comment by jacque006** [comment]
Good catch, corrected to https://github.com/web3well/bls-wallet/issues/190
