### ISSUE TITLE
Expose request & response in aggregator-proxy callback

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#433]
*As an* aggregator operator
*I would like to* be able to use the request & response objects when handling a bundle in `aggregator-proxy`
*So that I can* determine if I should accept a bundle via additional HTTP request information and respond appropriately.

**Comment by voltrevo** [comment]
@jacque006 Are we sure we want to support `aggregator-proxy` this way?

It's a pretty small change, so maybe this is a good little win.

However, I think we should be mindful of the direction here. Right now, `aggregator-proxy` is more of a suggestion... it's suitable for forking or even just inspiration.

If we expand upon it with more features, it becomes more like *the* tool you're supposed to use to get this done. Maybe that's something we want, but it requires a higher level of commitment from us, and comes at an increased cost for those who are more interested in directly using the code itself, rather than as a black box that's just supposed to work.

**Comment by jacque006** [comment]
I would agree with you that we want to be careful that we don't add too much functionality to this component. However, since this is running as a proxy/"middleware" against an aggregator instance, it makes sense to expose/allow hooks to certain things such as:
- Bundle for introspection/additions
- HTTP request/responses for introspection/verification/mutation
- (maybe) ability to add HTTP middleware via Koa router.

Beyond that scope, people can copy/pasta this, fork it, or fork/implement their own aggregator.
