### ISSUE TITLE
Investigate DevX of Aggregator

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#498]
Compare with similar tools, such as:
- https://github.com/stackup-wallet/stackup-bundler

**Comment by voltrevo** [comment]
@jzaki I'm a bit confused about whether you were more interested in the devX of running the aggregator/bundler or the devX of using an existing instance (ie, using the api).

For now I'm looking at a bit of both.

**Comment by voltrevo** [comment]
Not sure if they have more docs or not. Their link is currently broken: https://github.com/stackup-wallet/stackup-bundler/issues/91.

**Comment by voltrevo** [comment]
Getting up and running basically works as described.

You need to edit the `.env` file to set the URL of the node you're going to use (eg localhost:8545). This isn't included in their readme steps.

One thing that's really nice here is it doesn't rely on an external database. They use [BadgerDB](https://github.com/dgraph-io/badger) which just stores the data in `/tmp/stackup_bundler`.

We could get a similar benefit by porting to sqlite. This would just rely on a file, which also means the perms are tied to filesystem access, and so we wouldn't need any database config.

**Comment by voltrevo** [comment]
As for the experience using the API, it's unclear right now.

It seems to be just-the-standard. They use json-rpc just like a node, and provide the `eth_sendUserOperation` method as described in the EIP.

It's hard to test because 4337 doesn't prescribe the wallet to use. Presumably stackup tests with their own smart contract wallets (seems to be their main thing), or some dev version of this. I could just wrangle something together but hopefully there's an easier way. This is also required to see what kind of logs the bundler generates, which is part of the devX.

I'm going to park this temporarily since I'm waiting for feedback both from @jzaki ([earlier comment](https://github.com/web3well/bls-wallet/issues/498#issuecomment-1413127499)) and from stackup (https://github.com/stackup-wallet/stackup-bundler/issues/91, https://github.com/stackup-wallet/stackup-bundler/issues/92).

**Comment by hazim-j** [comment]
Hi @voltrevo! I'm the author of stackup bundler and happy to answer some of your questions here. Alternatively, happy to also chat in our discord since we're generally more active there. Strange that the invite link didn't work for you, but you can [try this one too](https://discord.gg/ZaT8xySPv2).

> Not sure if they have more docs or not.

We recently did an overhaul of our documentation and I must have missed updating this link. The updated bundler docs can be read [here](https://docs.stackup.sh/docs/packages/bundler/install).

> You need to edit the .env file to set the URL of the node you're going to use (eg localhost:8545). This isn't included in their readme steps.

Thanks for spotting this, I'll have to take a look into refreshing the readme soon. In the mean time we do document most of the config variables [here](https://docs.stackup.sh/docs/packages/bundler/configure). Although there are a couple new ones missing which I will also need to add. But you can also see [config/values.go](https://github.com/stackup-wallet/stackup-bundler/blob/main/internal/config/values.go) for the full list.

> It's hard to test because 4337 doesn't prescribe the wallet to use. Presumably stackup tests with their own smart contract wallets (seems to be their main thing), or some dev version of this.

So there are primarily two ways we test our bundler.
1. Using our [erc-4337-examples repo](https://github.com/stackup-wallet/erc-4337-examples). This and our [quickstart guide](https://docs.stackup.sh/docs/guides/quickstart) is generally what we share with other developers looking to jump in and test out an end to end UserOperation flow.
2. We also use the [bundler-spec-tests](https://github.com/eth-infinitism/bundler-spec-tests) as a more formal way of checking that the bundler is compliant with the EIP.

**Comment by jzaki** [comment]
> @jzaki I'm a bit confused about whether you were more interested in the devX of running the aggregator/bundler or the devX of using an existing instance (ie, using the api).

@voltrevo the general point is to ensure the BLS Wallet aggregator dev exp was at a point that you and the team are comfortable with. I gave Stackup as an example that was somewhat comparable, not pursuing 4337 bundling/use specifically.

**Comment by voltrevo** [comment]
Thanks @hazim-j 🙌.

@jzaki Gotcha. Shifting focus to improving docker support and possibly switching to sqlite.
